### ISSUE TITLE
Revise variable names to align with changes to `element-calcium-imaging`

### ISSUE THREAD

**Issue by CBroz1** [datajoint/element-miniscope#26]
See [this discussion](https://github.com/datajoint/element-miniscope/pull/13#discussion_r860137388). By aligning variable names across schemas (e.g., `acquisition_software` -> `acq_software`), we allow users' understanding of one to transfer to the other via stylistic consistency. 

Revert miniscope where possible to calcium-imaging convention?

**Comment by tdincer** [comment]
This is a big operation as it's not backward compatible. It would affect the SciOps operations.

**Comment by CBroz1** [comment]
@kabilar - Therefore miniscope should change to match calcium imaging, or we should carry the differences?

**Comment by kabilar** [comment]
Thanks @CBroz1 @tdincer.  Let's revert this change.  I had made the `acq_software` to `acquisition_software` update since this field was now in the sessions CSV file.  And the user would have to interpret the `acq_software` heading. Since this update would involve many repositories, we can revert `acquisition_software` to `acq_software`.

**Comment by CBroz1** [comment]
I've identified the following places where I plan to make changes/preserve differences
- Revise table structure to reflect Element Calcium imaging
    - acquisition_software -> acq_software
    - recording_directory: remove in favor of session.SessionDirectory
    - Segmentation.Mask.mask_id -> mask to reflect calcium-imaging
    - Move MaskType to after ProcessingParamSet to match ordering
    - extraction_method varchar(200) -> varchar(32)
- Preserving differences
    - AnatomicalLocation differs, but this is workflow-calcium-imaging bug (see [#57)](https://github.com/datajoint/element-calcium-imaging/issues/140)
    - RecordingInfo.File has a file_id that calcium-imaging does not. Paths should be secondary attributes in case they change
    - Many tables in calcium imaging permit z-depth information. Miniscope is 2D for now

**Comment by kabilar** [comment]
Thanks @CBroz1.  I agree.

For the location issue, I believe it is this link: https://github.com/datajoint/element-calcium-imaging/issues/140

**Comment by CBroz1** [comment]
> For the location issue, I believe it is this link: [datajoint/element-calcium-imaging#140](https://github.com/datajoint/element-calcium-imaging/issues/140)

Oops. Yes, that's correct. Fixed above
