### ISSUE TITLE
Table design issues

### ISSUE THREAD

**Issue by shenshan** [datajoint/element-miniscope#6]
Here are some specific points that worth asking UCLA miniscope users:

1. RecordingInfo (ScanInfo):
Should we keep x, y, z? What is the meaning for coordinates for miniscope? Columbia users suggest to remove them.
2. Does UCLA miniscope users do preprocessing like crop the frames?
3. Do we have a data example of multiple planes?

**Comment by CBroz1** [comment]
@kabilar - Are there any items here I should include in my next round of updates? If not, we can close the issue. It seems like changes have been made since to exclude depth/plane information for this element.

**Comment by kabilar** [comment]
Thanks @CBroz1.
1.We have removed the x,y,z positions.
2-3.As we engage with more users, we can add features in the future if they perform pre-processing or acquire multi-plane data.
